
[chat]

	[chat.dialogue_skipper]
		pesthunter_phillip = true
		maxwell = true
		lone_adventurer = true
		sam = true

	[chat.sending]
		fake_emojis = true

	[chat.blockers]
		block_sky_mall_messages = true

[bingo]
	only_on_bingo = true

	[bingo.chat]
		copy_achievements = true

	[bingo.community_goal_display]
		community_goal_display = true

	[bingo.chicken_head_timer]
		hide_egg_laid_message = false
		chicken_head_timer = true

	[bingo.blockers]
		baker_blocker = true

	[bingo.party]
		block_party_travel_messages = false

[commands]
	century_cake_island = "hunterhihunter"
	skycrypt_auto_open = true

