
[npc]

	[npc.dialogue_skipper]
		pesthunter_phillip = true
		maxwell = true
		lone_adventurer = true
		sam = true

[general]
	only_on_bingo = true

[bingo]
	community_goal_display = true

	[bingo.timers]
		chicken_head_timer = false

	[bingo.chat]
		copy_achievements = true

	[bingo.blockers]
		baker_blocker = true

