
[npc]

	[npc.dialogue_skipper]
		pesthunter_phillip = true
		maxwell = true
		lone_adventurer = true
		sam = true

[general]
	only_on_bingo = true

[chat]

	[chat.dialogue_skipper]
		pesthunter_phillip = true
		maxwell = true
		lone_adventurer = true
		sam = true

	[chat.sending]
		fake_emojis = true

	[chat.blockers]
		block_sky_mall_messages = false

	[chat.party]
		disable_party_travel_messages = true

[bingo]
	community_goal_display = true
	only_on_bingo = true

	[bingo.timers]
		chicken_head_timer = false

	[bingo.chat]
		copy_achievements = true

	[bingo.blockers]
		baker_blocker = true

	[bingo.chicken_head_timer]
		hide_egg_laid_message = true
		chicken_head_timer = true

	[bingo.commuity_goal_display]
		community_goal_display = true

	[bingo.party]
		disable_party_travel_messages = true
		block_sky_mall_messages = false
		block_party_travel_messages = true

