name: Module artefact

on:
  push:
    branches:
      - main

jobs:
  zip:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Check out repository
        uses: actions/checkout@v3

      # Step 2: Create BingoPlus folder and move contents into it
      - name: Organize files into BingoPlus folder
        run: |
          mkdir BingoPlus
          shopt -s extglob
          mv !(BingoPlus|.github|.git|README.md|LICENSE) BingoPlus/

      # Step 3: Zip the BingoPlus folder
      - name: Create zip archive
        run: |
          zip -r BingoPlus.zip BingoPlus

      # Step 4: Upload the zip archive
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: BingoPlus
          path: BingoPlus.zip
