name: Module artefact

on:
  push:
    branches:
      - main

jobs:
  create-folder-artifact:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Check out repository
        uses: actions/checkout@v3

      # Step 2: Create BingoPlus folder with the required contents
      - name: Organize files into BingoPlus folder
        run: |
          mkdir BingoPlus
          shopt -s extglob
          mv !(BingoPlus|.github|.git|README.md|LICENSE) BingoPlus/

      # Step 3: Upload the BingoPlus folder as an artifact
      - name: Upload BingoPlus folder as artifact
        uses: actions/upload-artifact@v3
        with:
          name: BingoPlus-archive
          path: BingoPlus
