name: Module artefact

on:
  push:
    branches:
      - main

permissions:
  contents: write  # Allows creating releases

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Check out repository
        uses: actions/checkout@v3

      # Step 2: Read version from metadata.json
      - name: Extract version from metadata.json
        id: get_version
        run: |
          version=$(jq -r '.version' metadata.json)
          echo "version=$version" >> $GITHUB_ENV

      # Step 3: Create BingoPlus folder and move contents into it, excluding specified files
      - name: Organize files into BingoPlus folder
        run: |
          mkdir BingoPlus
          shopt -s extglob
          mv !(BingoPlus|.github|.git|README.md|LICENSE) BingoPlus/

      # Step 4: Zip the BingoPlus folder, excluding unnecessary files
      - name: Create zip archive
        run: |
          zip -r BingoPlus.zip BingoPlus -x "*.github/*" ".git/*" "README.md" "LICENSE"

      # Step 5: Upload the zip archive as an artifact with the versioned name
      - name: Upload versioned artifact
        uses: actions/upload-artifact@v3
        with:
          name: BingoPlus-${{ env.version }}
          path: BingoPlus.zip

      # Step 6: Create a release with the versioned name and upload the zip as a release asset
      - name: Create GitHub Release
        uses: actions/create-release@v1
        with:
          tag_name: BingoPlus-${{ env.version }}
          release_name: BingoPlus-${{ env.version }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Step 7: Upload the BingoPlus.zip file to the release as an asset
      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: BingoPlus.zip
          asset_name: BingoPlus-${{ env.version }}.zip
          asset_content_type: application/zip
