name: Module artefact

on:
  push:
    branches:
      - main

jobs:
  zip:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Check out repository
        uses: actions/checkout@v3

      # Step 2: Create zip archive without an inner folder
      - name: Create zip archive
        run: |
          zip -r BingoPlus.zip . -x "*.github/*" ".git/*" "README.md" "LICENSE"

      # Step 3: Upload the artifact
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: BingoPlus
          path: BingoPlus.zip
